name: safe_vision
description: Safe Vision Full Project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^17.1.0
  fl_chart: ^1.1.1
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.4.0
  google_fonts: ^8.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/